
version: 2

models:
  - name: recentchanges
    description: "Streaming Wikimedia event data"
    columns:
      - name: r_schema
      - name: bot
      - name: comment
      - name: id
      - name: length_new
      - name: length_old
      - name: meta_uri,
      - name: meta_id
      - name: minor
      - name: namespace
      - name: parsedcomment
      - name: revision_new
      - name: revision_old
      - name: server_name
      - name: server_script_path
      - name: server_url
      - name: r_ts
      - name: title
      - name: type
      - name: user
      - name: wiki
  - name: useredits
    description: "Edit counts per user"
    columns:
      - name: user
        description: "The user"
        tests:
          - not_null
      - name: changes
        description: "The number of edits made by the user"
  - name: top10
    description: "Top 10 Wikipedia editors since the stream started"
    columns:
      - name: user
        description: "The user"
        tests:
          - not_null
      - name: changes
        description: "The number of edits made by the user"
